myfirst/myfirst/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('todo/', include('todo.urls')),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
]

myfirst/todo/urls.py
from django.urls import path

from . import views
from . import services

app_name = 'todo'

urlpatterns = [
	path('', views.Index.as_view(), name=''),
	path('index', views.Index.as_view(), name='index'),
	path('all_tasks', views.ShowAllTasks.as_view(), name='all_tasks'),
	path('completed_tasks', views.ShowCompletedTasks.as_view(), name='completed_tasks'),
	path('uncompleted_tasks', views.ShowUncompletedTasks.as_view(), name='uncompleted_tasks'),
	# Добавление/Удаление задач 
	path('create_task', views.CreateTaskView.as_view(), name='create_task'),
	path('delete_task/<int:pk>', views.DeleteTaskView.as_view(), name='delete_task'),
	# Добавление/Удаление комментариев	
	path('create_comment', views.CreateCommentView.as_view(), name='create_comment'),
	path('delete_comment/<int:pk>', views.DeleteCommentView.as_view(), name='delete_comment'),
	# Изменение текста и заголовка задачи 
	path('update_task/<int:pk>', views.UpdateTaskView.as_view(), name='update_task'),
	# Изменение статуса сообщения (выполнено/невыполнено)
	path('completed/<int:pk>', views.SetCompletedStatusView.as_view(), name='completed'),
	path('uncompleted/<int:pk>', views.SetUncompletedStatusView.as_view(), name='uncompleted'),
	# Регистрация/авторизация/выход пользователя
	path('register', views.RegisterUserView.as_view(), name='register'),
	path('login/', views.LoginUserView.as_view(), name='login'),
	path('logout', views.LogoutUserView.as_view(), name='logout'),
	# Api для ajax
	path('api_set_completed_status', services.api_set_completed_status, name='api_set_completed_status'),
	path('api_set_uncompleted_status', services.api_set_uncompleted_status, name='api_set_uncompleted_status'),
	path('api_append_task', services.api_append_task, name='api_append_task'),
	path('api_delete_task', services.api_delete_task, name='api_delete_task'),
	path('api_append_comment', services.api_append_comment, name='api_append_comment'),
	path('api_delete_comment', services.api_delete_comment, name='api_delete_comment'),
]

myfirst/todo/models.py
from django.db import models
from django.contrib.auth.models import User



class Task(models.Model):
	author = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
	title = models.CharField('Название задачи', max_length=150)
	text = models.TextField('Описание задачи')
	completed = models.BooleanField(default=0)

	def __str__(self):
		return self.title


	def is_completed(self):
		return self.completed


	class Meta:
		verbose_name = 'Задача'
		verbose_name_plural = 'Задачи'


class Comment(models.Model):
	task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='comments')
	text = models.CharField('Комментарий', max_length=200)


	def __str__(self):
		return self.text

	class Meta:
		verbose_name = 'Комментарий'
		verbose_name_plural = 'Комментарии'

myfirst/todo/forms.py
from django.forms import ModelForm, TextInput, PasswordInput, Textarea, EmailInput
from django.forms import CharField, EmailField
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


from .models import (Task, Comment)


class TaskForm(ModelForm):

	class Meta:
		model = Task
		fields = ['title', 'text']

		widgets = {
			'title': TextInput(attrs={
				'type': 'input',  
				'class': 'form-control',
				'id': 'exampleFormControlInput1',
				'placeholder': 'коротко о задаче',
			}),

			'text': Textarea(attrs={
				'class': 'form-control',
				'id': 'exampleFormControlTextarea1',
				'rows': '5',
				'placeholder': 'детальное описание задачи',
			}),
		}


class CommentForm(ModelForm):
	class Meta:
		model = Comment
		fields = ['text']

		widgets = {
			'text': Textarea(attrs={
				'class': 'form-control',
				'id': 'exampleFormControlTextarea1',
				'rows': '5',
				'placeholder': 'детальное описание задачи',
			}),
		}


class UserLoginForm(AuthenticationForm):
	username = CharField(label='Имя пользователя',
					widget=TextInput(attrs={'class': 'form-control'}))

	password = CharField(label='Пароль',
					widget=PasswordInput(attrs={'class': 'form-control'}))


class UserRegisterForm(UserCreationForm):
	username = CharField(label='Имя пользователя',
						widget=TextInput(attrs={
							'class': 'form-control',
							'placeholder': 'Имя пользователя',
							'required': '',
						}))

	password1 = CharField(label='Пароль',
						widget=PasswordInput(attrs={
							'class': 'form-control',
							'placeholder': 'Пароль',
							'required': '',
						}))

	password2 = CharField(label='Повторите пароль',
						widget=PasswordInput(attrs={
							'class': 'form-control',
							'placeholder': 'Повторите пароль',
							'required': '',
						}))

	email = EmailField(label='Укажите e-mail',
						widget=EmailInput(attrs={
							'class': 'form-control',
							'placeholder': 'e-mail',
						}))


	class Meta:
		model = User
		fields = ('username', 'email', 'password1', 'password2')

myfirst/todo/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseForbidden, HttpResponseNotFound
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.models import User

from .models import Task, Comment
from .forms import TaskForm, CommentForm
from .forms import UserRegisterForm, UserLoginForm

from .services import change_task_status


class BasePageView(LoginRequiredMixin, ListView):
	""" Супер класс, от которого наследуются все классы генерирующие главную страницу """
	model = Task
	template_name = 'todo/todo.html'
	context_object_name = 'tasks'
	title = ''
	extra_context = {}
	# login_url = None # Я указал адрес для авторизации в настройках

	# Перезапись метода родительского класса ListView унаследуваного от BaseListView->MultipleObjectMixin
	def get_context_data(self, *, object_list=None, **kwargs):
		context = super().get_context_data(**kwargs)
		context['title'] = self.title
		context.update(self.extra_context)
		return context 

	# Перезапись метода родительского класса ListView унаследуваного от BaseListView->MultipleObjectMixin
	def get_queryset(self):
		# order_by('-id') разворачивает задания, чтобы более старые были внизу списка
		return Task.objects.filter(author=self.request.user).order_by('-id')


class BaseCreateFormView(LoginRequiredMixin, CreateView):
	success_url = reverse_lazy('todo:index')
	title = ''
	extra_context = {}
	# login_url = None # Я указал адрес для авторизации в настройках

	# Перезапись метода родительского класса CreateView унаследуваного от BaseListView->MultipleObjectMixin
	def get_context_data(self, *, object_list=None, **kwargs):
		context = super().get_context_data(**kwargs)
		context['title'] = self.title
		context.update(self.extra_context)
		return context


class Index(BasePageView):
	""" Рендерит главную страницу """

	title = 'Главная страница'


class ShowAllTasks(BasePageView):
	""" Рендерит главную страницу со всеми типами задач """

	title = 'Все задачи'
	extra_context = {'filter': 'all_tasks'}


class ShowCompletedTasks(BasePageView):
	""" Рендерит главную страницу только с выполненными задачами """

	title = 'Выполненные задачи'
	extra_context = {'filter': 'completed_tasks'}

	# Перезапись метода родительского класса BasePageView
	def get_queryset(self):
		return Task.objects.filter(author=self.request.user, completed=True).order_by('-id')


class ShowUncompletedTasks(BasePageView):
	""" Рендерит главную страницу только с выполненными задачами """

	title = 'Невыполненные задачи'
	extra_context = {'filter': 'uncompleted_tasks'}

	# Перезапись метода родительского класса BasePageView
	def get_queryset(self):
		return Task.objects.filter(author=self.request.user, completed=False).order_by('-id')


class CreateTaskView(BaseCreateFormView):
	""" Создание задачи """
	form_class = TaskForm
	template_name = 'todo/create_task.html'
	title = 'Добавление задания'

	# Перезапись метода родительского класса CreateView унаследуваного от ModelFormMixin
	def form_valid(self, form):
		self.object = form.save(commit=False)
		self.object.author = self.request.user
		self.object.save()
		return super().form_valid(form)


class DeleteTaskView(LoginRequiredMixin, DeleteView):
	""" Удаление задачи """

	def get(self, request, pk):
		try:
			task = Task.objects.get(id=pk)
			task.delete()
		except:
			return HttpResponseNotFound(render(request, 'todo/404.html'))
		else:
			return redirect('todo:index')


	def post(self, request, post):
		return HttpResponseNotFound(render(request, 'todo/403.html'))


class CreateCommentView(BaseCreateFormView):
	""" Создание комментария """
	form_class = CommentForm
	template_name = 'todo/create_comment.html'
	title = 'Добавление комментария'

	def get_context_data(self, *, object_list=None, **kwargs):
		context = super().get_context_data(**kwargs)
		context['title'] = self.title
		context['task_id'] = self.request.GET.get('task_id')
		return context

	# Перезапись метода родительского класса CreateView унаследуваного от ModelFormMixin
	def form_valid(self, form):
		self.object = form.save(commit=False)
		self.object.task_id = self.request.POST.get('task_id')
		self.object.save()
		return super().form_valid(form)


class DeleteCommentView(LoginRequiredMixin, DeleteView):
	""" Удаление комментария """

	def get(self, request, pk):
		try:
			task = Comment.objects.get(id=pk)
			task.delete()
		except:
			return HttpResponseNotFound(render(request, 'todo/404.html'))
		else:
			return redirect('todo:index')


	def post(self, request, post):
		return HttpResponseNotFound(render(request, 'todo/403.html'))


class UpdateTaskView(BaseCreateFormView, UpdateView):
	""" Изменение заголовка и текста задачи """
	model = Task
	form_class = TaskForm
	template_name = 'todo/update_task.html'
	title = 'Изменение задания'


class SetCompletedStatusView(BasePageView):
	""" Установка выполненного состояния задачи """

	def get(self, request, pk):
		try:
			change_task_status(request, pk, is_completed=True)
		except:
			return HttpResponseNotFound(render(request, 'todo/404.html'))
		else:
			return redirect('todo:index')


	def post(self, request, post):
		return HttpResponseNotFound(render(request, 'todo/403.html'))


class SetUncompletedStatusView(BasePageView):
	""" Установка невыполненного состояния задачи """

	def get(self, request, pk):
		try:
			change_task_status(request, pk, is_completed=False)
		except:
			return HttpResponseNotFound(render(request, 'todo/404.html'))
		else:
			return redirect('todo:index')


	def post(self, request, post):
		return HttpResponseNotFound(render(request, 'todo/403.html'))


class RegisterUserView(CreateView):
	""" Регистрация пользователя """
	model = User
	form_class = UserRegisterForm
	template_name = 'todo/register.html'
	success_url = reverse_lazy('todo:index')


	def form_valid(self, form):
		form_valid = super().form_valid(form)
		username = form.cleaned_data['username']
		password = form.cleaned_data['password1']
		auth_user = authenticate(username=username, password=password)
		login(self.request, auth_user)
		return form_valid


class LoginUserView(LoginView):
	""" Авторизация пользователя """
	model = User
	form_class = UserLoginForm
	template_name = 'todo/login.html'
	success_url = reverse_lazy('todo:index')


class LogoutUserView(LogoutView):
	""" Выход пользователя с личного кабинета"""
	next_page = reverse_lazy('todo:login')

myfirst/todo/templates/todo/create_comment.html
{% extends 'todo/index.html' %}


{% block title %}
  Добавление новой задачи
{% endblock %} 

{% block header %}
  <header class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <p class="h5 my-0 me-md-auto fw-normal my-1">#Todo <span class="blockquote-footer">просто запиши это</span></p>
  <a type="button" class="btn btn-outline-danger" href="{% url 'todo:index' %}">Назад к задачам</a>
  </header>
{% endblock %}


<!-- Добавление новой задачи-->
{% block content %} 
  <form action="{% url 'todo:create_comment' %}" method="post">
    {% csrf_token %}
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Добавление комментария</h5>
        </div>

        <div class="modal-body">  
          <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Комментарий</label>
            {{form.text}}
        </div>

        <div class="modal-footer">
          <a type="button" class="btn btn-secondary" href="{% url 'todo:index' %}">Отмена</a>
          <button type="submit" class="btn btn-primary">Добавить</button>
        </div>
        <input type="hidden" name="task_id" value="{{task_id}}">
      </div>
    </div>
  </form>
{% endblock %}

myfirst/todo/templates/todo/create_task.html
{% extends 'todo/index.html' %}


{% block title %}
    Добавление новой задачи
{% endblock %} 


{% block header %}
  <header class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <p class="h5 my-0 me-md-auto fw-normal my-1">#Todo <span class="blockquote-footer">просто запиши это</span></p>
    <a type="button" class="btn btn-outline-danger" href="{% url 'todo:index' %}">Назад к задачам</a>
  </header>
{% endblock %}


<!-- Добавление новой задачи-->
{% block content %} 
  <form action="{% url 'todo:create_task' %}" method="post">
    {% csrf_token %}
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Добавление задачи</h5>
          </div>
          <div class="modal-body">
            <div class="mb-3">
              <label for="exampleFormControlInput1" class="form-label">Имя задачи</label>
                {{form.title}}
            </div>
            <div class="mb-3">
              <label for="exampleFormControlTextarea1" class="form-label">Описание</label>
                {{form.text}}
            </div>
          </div>
          <div class="modal-footer">
            <a type="button" class="btn btn-secondary" href="{% url 'todo:index' %}">Отмена</a>
            <button type="submit" class="btn btn-primary">Добавить</button>
          </div>
        </div>
        {% if error %}
          <div class="alert alert-danger mt-3" role="alert">{{error}}</div>
        {% endif %}
        </div>
      </div>
  </form>
{% endblock %}

myfirst/todo/templates/todo/index.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Мой сайт первый на Django{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css'%}">
    <!-- этот токен использует javascript для подписи всех ajax запросов -->
    {% csrf_token %}
  </head>

  <body>
    {% block header %}
      <header class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
        <p class="h5 my-0 me-md-auto fw-normal my-1">#Todo <span class="blockquote-footer">просто запиши это</span></p>
        
        {% if request.user.is_authenticated %}
          <a class="btn btn-outline-danger" href="{% url 'todo:logout' %}">Выйти</a>
        {% else %}
          <a class="btn btn-outline-primary" href="{% url 'todo:login' %}">Войти</a>
        {% endif %}

     </header>
    {% endblock %}

    {% block content %} {% endblock %}
  
  </body>
</html>

myfirst/todo/templates/todo/login.html
{% extends 'todo/index.html' %}


{% block title %} Авторизация пользователя {% endblock %}

{% block filter %}{% endblock %}

{% block content %}
    <div class="d-flex justify-content-center text-center">
        <main class="form-signin d-flex">
            <form action="{% url 'todo:login' %}" method="post">
                <h1 class="h3 mb-3 fw-normal">Авторизация</h1>
                {% csrf_token %}
                {{ form.as_p }}
                <button class="w-100 btn btn-lg btn-primary" type="submit">Войти</button>
                <a class="text-decoration-none" href="{% url 'todo:register' %}">Регистрация</a>
            </form>
        </main>
    </div>
{% endblock %}

myfirst/todo/templates/todo/modal_append_comment.html
<!-- Модальное окно для создания комментария -->
{% block modal_append_comment %}
  <div class="modal fade" id="addComment" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Добавление комментария</h5>
      </div>
        <div class="modal-body">
          <div class="mb-3">
            <label for="comment-body" class="form-label">Комментарий</label>
            <textarea class="form-control" id="comment-body" name="text"></textarea>
            <input type="hidden" class="form-control" name="task_id" id="comment-task-id"></input>
            {% csrf_token %}
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" 
            data-bs-dismiss="modal">Отмена</button>
          <button type="button" class="btn btn-primary" data-bs-dismiss="modal" 
            onclick="api_append_comment('{% url "todo:api_append_comment" %}')">Добавить</button>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

myfirst/todo/templates/todo/register.html
{% extends 'todo/index.html' %}


{% block title %} Регистрация пользователя {% endblock %}

{% block filter %}{% endblock %}

{% block content %}
  <div class="d-flex justify-content-center text-center">
    <main class="form-signin d-flex">
        <form action="{% url 'todo:register' %}" method="post">
        <h1 class="h3 mb-3 fw-normal">Регистрация</h1>
        {% csrf_token %}
        {{ form.as_p }}
        <button class="w-100 btn btn-lg btn-primary" type="submit">Зарегистрироваться</button>
    </form>
    </main>
    </div>
  </div>
{% endblock %}

myfirst/todo/templates/todo/task_filter.html
<!-- Фильтр задач -->
{% block filter %}
<!-- Кнопки для отправки ajax запросов -->
<div class="js_filter_button">
  <div class="btn-group d-flex justify-content-center">
    <a id="js_filter_button_all" class="btn custom-btn js_filter_buttons custom-btn-hover d-none" 
      onclick=all_tasks()>Все задачи</a>

    <a id="js_filter_button_completed" class="btn custom-btn js_filter_buttons d-none" 
      onclick=completed_tasks()>Выполненые</a>

    <a id="js_filter_button_uncompleted" class="btn custom-btn js_filter_buttons d-none" 
      onclick=uncompleted_tasks()>Невыполненные</a>
  </div>    
</div>

<div class="url_filter_button">
  <div class="btn-group d-flex justify-content-center" role="group" aria-label="Basic radio toggle button group">

    <a class="btn custom-btn url_filter_buttons {% if filter == "all_tasks" %}custom-btn-hover{% endif %}" 
      for="btnradio1" href="{% url 'todo:all_tasks' %}">Все задачи</a>

    <a class="btn custom-btn url_filter_buttons {% if filter == "completed_tasks" %}custom-btn-hover{% endif %}" 
      for="btnradio2" href="{% url 'todo:completed_tasks' %}">Выполненые</a>

    <a class="btn custom-btn url_filter_buttons {% if filter == "uncompleted_tasks" %}custom-btn-hover{% endif %}"
      for="btnradio3" href="{% url 'todo:uncompleted_tasks' %}">Невыполненные</a>
  </div>
</div>
{% endblock %}

myfirst/todo/templates/todo/todo.html
{% extends 'todo/index.html' %}

{% block title %} {{title}} {% endblock %}

{% block content %}
  <!-- Блок предуприждения о работе js -->
  {% block  alert %}
    <div class="content">    
      <div id="test_working_js" class="alert alert-warning" role="alert">
        Включите javascript для корректной работы сайта
      </div>
    </div>
  {% endblock %}

  {% block modal_append_comment %}
    {% include 'todo/modal_append_comment.html' %}
  {% endblock %}

  {% block modal_append_task %}
    {% include 'todo/modal_append_task.html' %}
  {% endblock %}

  <div id='task-conteiner' class="container mt-3">
    <div class="accordion" id="accordionExample">

      <div id="accordion-header" class="accordion-item accordion-filter-buttons">
        {% block filter %}
          {% include 'todo/task_filter.html'%}
        {% endblock %}
      </div>

      {% for task in tasks %}
        <div id="accordion-item-{{task.id}}" 
          class="accordion-item task-state-{% if task.is_completed %}completed{% else %}uncompleted{% endif %}">
          <h2 class="accordion-header" id="headingOne">
            <button
              class="accordion-button {% if active_task != task.id %} not-collapsed-flag {% endif %} auto-collapsed-flag"
              type="button" 
              data-bs-toggle="collapse" 
              data-bs-target="#collapse{{task.id}}" 
              aria-expanded="true" 
              aria-controls="collapse{{task.id}}">
              
              <div class="{% if task.is_completed %} d-block {% else %} d-none {% endif %}" id="mark{{task.id}}"> 
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check2-square" viewBox="0 0 16 16">
                  <path d="M3 14.5A1.5 1.5 0 0 1 1.5 13V3A1.5 1.5 0 0 1 3 1.5h8a.5.5 0 0 1 0 1H3a.5.5 0 0 0-.5.5v10a.5.5 0 0 0 .5.5h10a.5.5 0 0 0 .5-.5V8a.5.5 0 0 1 1 0v5a1.5 1.5 0 0 1-1.5 1.5H3z"/>
                  <path d="M8.354 10.354l7-7a.5.5 0 0 0-.708-.708L8 9.293 5.354 6.646a.5.5 0 1  0-.708.708l3 3a.5.5 0 0 0 .708 0z"/>
                </svg>
              </div>      
              <span class="px-2">{{task.title}}</span>
            </button>
          </h2>
          <div id="collapse{{task.id}}" class="accordion-collapse auto-collapse-flag
            {% if active_task == task.id %} show {% endif %}" 
            aria-labelledby="headingOne" data-bs-parent="#accordionExample">
            <div class="accordion-body">{{task.text}}</div>

            <div id="comment-container-{{task.id}}">
              {% if task.comments %}
                {% for comment in task.comments.all reversed %}
                  <div id="comment-body-{{comment.id}}" class="accordion-body my-0 py-1">      
                    <div class="alert alert-secondary py-1 my-0" role="alert">
                      <div class="row g-3">
                        <!-- Кнопки для отправки ajax запросов -->
                        <a type="button" class="col-auto btn-close js_buttons d-none" 
                           onclick="make_delete_comment_requests('{% url "todo:api_delete_comment" %}', {{comment.id}})">
                        </a>
                      
                        <!-- Кнопка для работы по GET запросам -->
                        <a type="button" class="col-auto btn-close url_buttons d-flex" 
                            href="{% url 'todo:delete_comment' comment.id %}">
                        </a>

                        <div class="col-auto"><span>{{comment.text}}</span></div>
                        <div class="col-auto"></div>
                      </div> 
                    </div>
                  </div>
                {% endfor %}
              {% endif %}
            </div>
            <!-- Кнопки для отправки ajax запросов -->
            <div class=".container accordion-body js_buttons d-none">  

              <div id="complete-control-button{{task.id}}" class="{% if task.is_completed %} d-flex {% else %} d-none {% endif %}">
                <button type="button" class="me-1 btn btn-outline-warning"
                  onclick="make_change_task_status_requests('{% url "todo:api_set_uncompleted_status" %}', {{task.id}})">Снять отметку</button>
              </div>

              <div id="uncomplete-control-button{{task.id}}" class="{% if task.is_completed %} d-none {% else %} d-flex {% endif %}">
                <button type="button" class="me-1 btn btn-outline-primary"
                  onclick="make_change_task_status_requests('{% url "todo:api_set_completed_status" %}', {{task.id}})">Отметить как выполненая</button>        
              </div>

              <button type="button" class="me-1 btn btn-outline-secondary" data-bs-toggle="modal" 
                data-bs-target="#addComment" onclick="add_task_id_to_modal_form({{task.id}})">
                Добавить комментарий
              </button>
             
              <button type="button" class="me-1 btn btn-outline-danger" 
                onclick="make_delete_task_requests('{% url "todo:api_delete_task" %}', {{task.id}})">Удалить задачу</button>

                <a type="button" class="me-1 btn btn-outline-success"
                  href="{% url 'todo:update_task' task.id %}">Изменить</a>
            </div>

            <!-- Кнопки для работы по GET запросам -->
            <div class=".container accordion-body url_buttons d-flex">  
              {% if task.is_completed %}
                <a type="button" class="btn btn-outline-warning {% if task.is_completed %} d-flex {% else %} d-none {% endif %} me-1"
                  href="{% url 'todo:uncompleted' task.id %}">Снять отметку</a>
              {% else %}
                <a type="button" class="btn btn-outline-primary {% if task.is_completed %} d-none {% else %} d-flex {% endif %} me-1" 
                  href="{% url 'todo:completed' task.id %}">Отметить как выполненая</a>
              {% endif %}
              
              <a type="button" class="btn btn-outline-secondary me-1" 
                href="{% url 'todo:create_comment' %}?task_id={{task.id}}">Добавить комментарий</a>
              
              <a type="button" class="btn btn-outline-danger me-1" 
                href="{% url 'todo:delete_task' task.id %}">Удалить задачу</a>

              <a type="button" class="me-1 btn btn-outline-success"
                href="{% url 'todo:update_task' task.id %}">Изменить</a>

            </div>
          
          </div>
        </div>
      {% endfor %}

      <div id="accordion-item" class="accordion-item">
          <button class="btn accordion-add-button justify-content-center js_buttons d-none" data-bs-toggle="modal" data-bs-target="#addTask">
            <span>Добавить задачу</span>
          </button>

          <button class="btn accordion-add-button justify-content-center url_buttons">
            <a class="text-decoration-none" href="{% url 'todo:create_task' %}">Добавить задачу</a>
          </button>
      </div>
    </div>

    <div id="empty-tasks-alert" class="{% if tasks %} d-none {% else %} d-block {% endif %}">
      <div class="alert alert-secondary my-3 d-flex justify-content-center" role="alert"> У вас, пока-что, нет никаких задач. Добавьте задачу, чтобы не забыть о ней!</div>
    </div>

    {% load static %}
    <script src="{% static 'js/scripts.js'%}" type="text/javascript"></script>
  </div>
{% endblock %}